# Generated by Django 2.2.12 on 2020-05-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0006_2_3'),
        ('plans', '0005_create_user_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerplan',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='If the subscription has been canceled ``cancel_at_period_end`` on the subscription will be true. You can use this attribute to determine whether a subscription that has a status of active is scheduled to be canceled at the end of the current period.'),
        ),
        migrations.AddField(
            model_name='customerplan',
            name='canceled_at',
            field=models.DateTimeField(blank=True, help_text='If the subscription has been canceled, the date of that cancellation. If the subscription was canceled with ``cancel_at_period_end``, canceled_at will still reflect the date of the initial cancellation request, not the end of the subscription period when the subscription is automatically moved to a canceled state.', null=True),
        ),
        migrations.AddField(
            model_name='customerplan',
            name='default_payment_method',
            field=models.ForeignKey(blank=True, help_text='The default payment method for the subscription. It must belong to the customer associated with the subscription. If not set, invoices will use the default payment method in the customer’s invoice settings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='djstripe.DjstripePaymentMethod'),
        ),
    ]
