# Generated by Django 2.2.12 on 2020-05-13 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0118_remove_userpermission_role'),
        ('plans', '0007_auto_20200512_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.CompanyRole'),
        ),
        migrations.AlterField(
            model_name='order',
            name='charge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djstripe.Charge'),
        ),
    ]
