# Generated by Django 2.2.12 on 2020-05-16 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_auto_20200513_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.Country'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='buyer_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_buyer_country', to='cities_light.Country'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issuer_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.Country'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipping_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_shipping_country', to='cities_light.Country'),
        ),
    ]
