# Generated by Django 2.2.12 on 2020-05-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_auto_20200516_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
