# Generated by Django 2.2.12 on 2020-05-16 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0118_remove_userpermission_role'),
        ('plans', '0010_billinginfo_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='default',
            field=models.NullBooleanField(db_index=True, default=None, help_text='Both "Unknown" and "No" means that the plan is not default'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.CompanyRole'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('role', 'default')},
        ),
    ]
